version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_storage:/data/db

  auth-service:
    build: ./auth_service
    container_name: auth-service
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "${AUTH_API_PORT}:${AUTH_API_PORT}"
    environment:
      API_PORT: ${AUTH_API_PORT}
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=admin

volumes:
  mongo_storage:
